import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

import {
  stableCommerceArtifact,
  pageTypeLabels,
  stableThemeArtifacts,
  type GeneratedThemeArtifact,
  type GenerationResult,
  type ReferenceAnalysis,
  type ThemeMapping
} from "@shopify-web-replicator/shared";

type GenerateInput = {
  analysis: ReferenceAnalysis;
  mapping: ThemeMapping;
};

function sectionTypeFromPath(sectionPath: string): string {
  return basename(sectionPath, ".liquid");
}

function schemaNameForPageType(pageType: ReferenceAnalysis["pageType"]): string {
  if (pageType === "homepage") {
    return "Generated homepage";
  }

  if (pageType === "product_page") {
    return "Generated product";
  }

  if (pageType === "collection_page") {
    return "Generated collection";
  }

  return "Generated landing";
}

function renderCommerceWiringSnippet(pageType: ReferenceAnalysis["pageType"]): string {
  const snippetType = basename(stableCommerceArtifact.path, ".liquid");

  return `
    {% render '${snippetType}', page_type: '${pageType}' %}
`;
}

function renderMarketingSection(
  sectionType: string,
  analysis: ReferenceAnalysis,
  mapping: ThemeMapping
): string {
  const primarySection = mapping.sections[0];

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="${sectionType} full-width">
  <div class="${sectionType}__content">
    {% if section.settings.eyebrow != blank %}
      <p class="${sectionType}__eyebrow">{{ section.settings.eyebrow }}</p>
    {% endif %}

    <h1>{{ section.settings.heading }}</h1>
    <p class="${sectionType}__body">{{ section.settings.body }}</p>
    <p class="${sectionType}__meta">{{ section.settings.mapping_summary }}</p>

    {% if section.settings.cta_label != blank and section.settings.cta_link != blank %}
      <a class="${sectionType}__cta" href="{{ section.settings.cta_link }}">
        {{ section.settings.cta_label }}
      </a>
    {% endif %}

${renderCommerceWiringSnippet(analysis.pageType)}
  </div>
</section>

{% stylesheet %}
  .${sectionType} {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background:
      radial-gradient(circle at top left, rgba(214, 237, 158, 0.9), transparent 28%),
      linear-gradient(180deg, #fffdf5 0%, #eef4df 100%);
  }

  .${sectionType}__content {
    grid-column: 2;
    padding: 0 24px;
    max-width: 720px;
  }

  .${sectionType}__eyebrow {
    margin: 0 0 1rem;
    text-transform: uppercase;
    letter-spacing: 0.14em;
    font-size: 0.82rem;
  }

  .${sectionType} h1 {
    margin: 0;
    font-size: clamp(2.75rem, 7vw, 5rem);
    line-height: 0.95;
  }

  .${sectionType}__body,
  .${sectionType}__meta {
    margin: 1.5rem 0 0;
    max-width: 60ch;
    font-size: 1.1rem;
    line-height: 1.5;
  }

  .${sectionType}__meta {
    font-size: 0.95rem;
    color: #335144;
  }

  .${sectionType}__cta {
    display: inline-flex;
    margin-top: 1.75rem;
    padding: 0.95rem 1.4rem;
    border-radius: 999px;
    text-decoration: none;
    color: #fffdf5;
    background-color: #17362b;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: schemaNameForPageType(analysis.pageType),
    settings: [
      {
        type: "text",
        id: "eyebrow",
        label: "Eyebrow",
        default: analysis.referenceHost
      },
      {
        type: "text",
        id: "heading",
        label: "Heading",
        default: primarySection?.heading ?? analysis.title
      },
      {
        type: "textarea",
        id: "body",
        label: "Body",
        default: primarySection?.body ?? analysis.summary
      },
      {
        type: "textarea",
        id: "mapping_summary",
        label: "Mapping summary",
        default: mapping.summary
      },
      {
        type: "text",
        id: "cta_label",
        label: "CTA label",
        default: primarySection?.ctaLabel ?? "Review generated output"
      },
      {
        type: "url",
        id: "cta_link",
        label: "CTA link"
      }
    ],
    presets: [
      {
        name: schemaNameForPageType(analysis.pageType)
      }
    ]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderProductSection(sectionType: string, analysis: ReferenceAnalysis, mapping: ThemeMapping): string {
  const primarySection = mapping.sections[0];

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="${sectionType} full-width">
  <div class="${sectionType}__content">
    <p class="${sectionType}__eyebrow">{{ section.settings.eyebrow }}</p>
    <h1>{{ product.title | default: section.settings.heading }}</h1>
    <p class="${sectionType}__body">{{ section.settings.body }}</p>
    <p class="${sectionType}__meta">{{ section.settings.mapping_summary }}</p>

    {% if product != blank %}
      <div class="${sectionType}__price">{{ product.price | money }}</div>
      {% form 'product', product %}
        <button class="${sectionType}__cta" type="submit">
          {{ section.settings.cta_label }}
        </button>
      {% endform %}
    {% else %}
      <p class="${sectionType}__empty">Connect this template to a product to validate the generated purchase flow.</p>
    {% endif %}

${renderCommerceWiringSnippet(analysis.pageType)}
  </div>
</section>

{% stylesheet %}
  .${sectionType} {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background: linear-gradient(180deg, #fffdf5 0%, #eef4df 100%);
  }

  .${sectionType}__content {
    grid-column: 2;
    padding: 0 24px;
    max-width: 760px;
  }

  .${sectionType}__eyebrow,
  .${sectionType}__meta,
  .${sectionType}__empty {
    color: #335144;
  }

  .${sectionType}__price {
    margin-top: 1.5rem;
    font-size: 1.25rem;
    font-weight: 700;
  }

  .${sectionType}__cta {
    margin-top: 1rem;
    padding: 0.95rem 1.4rem;
    border: 0;
    border-radius: 999px;
    color: #fffdf5;
    background-color: #17362b;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: schemaNameForPageType(analysis.pageType),
    settings: [
      {
        type: "text",
        id: "eyebrow",
        label: "Eyebrow",
        default: analysis.referenceHost
      },
      {
        type: "text",
        id: "heading",
        label: "Heading fallback",
        default: primarySection?.heading ?? analysis.title
      },
      {
        type: "textarea",
        id: "body",
        label: "Body",
        default: primarySection?.body ?? analysis.summary
      },
      {
        type: "textarea",
        id: "mapping_summary",
        label: "Mapping summary",
        default: mapping.summary
      },
      {
        type: "text",
        id: "cta_label",
        label: "CTA label",
        default: primarySection?.ctaLabel ?? "Add to cart"
      }
    ]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderCollectionSection(sectionType: string, analysis: ReferenceAnalysis, mapping: ThemeMapping): string {
  const primarySection = mapping.sections[0];

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="${sectionType} full-width">
  <div class="${sectionType}__content">
    <p class="${sectionType}__eyebrow">{{ section.settings.eyebrow }}</p>
    <h1>{{ collection.title | default: section.settings.heading }}</h1>
    <p class="${sectionType}__body">{{ section.settings.body }}</p>
    <p class="${sectionType}__meta">{{ section.settings.mapping_summary }}</p>

    <div class="${sectionType}__grid">
      {% for product in collection.products limit: 8 %}
        <article class="${sectionType}__card">
          <h2>{{ product.title }}</h2>
          <p>{{ product.price | money }}</p>
        </article>
      {% else %}
        <p class="${sectionType}__empty">Connect this template to a collection to validate the generated browsing flow.</p>
      {% endfor %}
    </div>

${renderCommerceWiringSnippet(analysis.pageType)}
  </div>
</section>

{% stylesheet %}
  .${sectionType} {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background: linear-gradient(180deg, #fffdf5 0%, #eef4df 100%);
  }

  .${sectionType}__content {
    grid-column: 2;
    padding: 0 24px;
  }

  .${sectionType}__grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 1rem;
    margin-top: 2rem;
  }

  .${sectionType}__card {
    padding: 1rem;
    border-radius: 1rem;
    background: rgba(17, 49, 38, 0.06);
  }

  .${sectionType}__meta,
  .${sectionType}__empty {
    color: #335144;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: schemaNameForPageType(analysis.pageType),
    settings: [
      {
        type: "text",
        id: "eyebrow",
        label: "Eyebrow",
        default: analysis.referenceHost
      },
      {
        type: "text",
        id: "heading",
        label: "Heading fallback",
        default: primarySection?.heading ?? analysis.title
      },
      {
        type: "textarea",
        id: "body",
        label: "Body",
        default: primarySection?.body ?? analysis.summary
      },
      {
        type: "textarea",
        id: "mapping_summary",
        label: "Mapping summary",
        default: mapping.summary
      }
    ]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderSection(analysis: ReferenceAnalysis, mapping: ThemeMapping): string {
  const sectionType = sectionTypeFromPath(mapping.sectionPath);

  if (analysis.pageType === "product_page") {
    return renderProductSection(sectionType, analysis, mapping);
  }

  if (analysis.pageType === "collection_page") {
    return renderCollectionSection(sectionType, analysis, mapping);
  }

  return renderMarketingSection(sectionType, analysis, mapping);
}

function renderTemplate(analysis: ReferenceAnalysis, mapping: ThemeMapping): string {
  const sectionType = sectionTypeFromPath(mapping.sectionPath);

  return JSON.stringify(
    {
      sections: {
        main: {
          type: sectionType,
          settings: {
            eyebrow: mapping.title,
            heading: mapping.sections[0]?.heading ?? mapping.title,
            body: mapping.sections[0]?.body ?? mapping.summary,
            mapping_summary: mapping.summary,
            ...(analysis.pageType !== "collection_page"
              ? { cta_label: mapping.sections[0]?.ctaLabel ?? "Review generated output" }
              : {})
          }
        }
      },
      order: ["main"]
    },
    null,
    2
  );
}

export class ShopifyThemeGenerator {
  constructor(readonly themeWorkspacePath: string) {}

  async generate({ analysis, mapping }: GenerateInput): Promise<{
    artifacts: GeneratedThemeArtifact[];
    generation: GenerationResult;
  }> {
    const artifacts = stableThemeArtifacts[analysis.pageType];
    await mkdir(dirname(join(this.themeWorkspacePath, mapping.sectionPath)), { recursive: true });
    await mkdir(dirname(join(this.themeWorkspacePath, mapping.templatePath)), { recursive: true });

    await writeFile(join(this.themeWorkspacePath, mapping.sectionPath), renderSection(analysis, mapping));
    await writeFile(join(this.themeWorkspacePath, mapping.templatePath), renderTemplate(analysis, mapping));

    const generatedAt = new Date().toISOString();

    return {
      artifacts: [
        {
          kind: "section",
          path: mapping.sectionPath,
          status: "generated",
          description: artifacts.sectionDescription,
          lastWrittenAt: generatedAt
        },
        {
          kind: "template",
          path: mapping.templatePath,
          status: "generated",
          description: artifacts.templateDescription,
          lastWrittenAt: generatedAt
        }
      ],
      generation: {
        generatedAt,
        templatePath: mapping.templatePath,
        sectionPath: mapping.sectionPath
      }
    };
  }
}
