import { mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

import {
  stableCommerceArtifact,
  stableThemeArtifacts,
  type GeneratedThemeArtifact,
  type GenerationResult,
  type ReferenceAnalysis,
  type ReferenceCapture,
  type ReferenceStyleTokens,
  type StorefrontModel,
  type ThemeMapping
} from "@shopify-web-replicator/shared";

type GenerateInput = {
  analysis: ReferenceAnalysis;
  mapping: ThemeMapping;
  capture?: ReferenceCapture;
  storefrontModel?: StorefrontModel;
};

function sectionTypeFromPath(sectionPath: string): string {
  return basename(sectionPath, ".liquid");
}

function schemaNameForPageType(pageType: ReferenceAnalysis["pageType"]): string {
  if (pageType === "homepage") return "Generated homepage";
  if (pageType === "product_page") return "Generated product";
  if (pageType === "collection_page") return "Generated collection";
  return "Generated landing";
}

function renderCommerceWiringSnippet(pageType: ReferenceAnalysis["pageType"]): string {
  const snippetType = basename(stableCommerceArtifact.path, ".liquid");
  return `
    {% render '${snippetType}', page_type: '${pageType}' %}
`;
}

function rgbToHex(rgb: string): string {
  const match = rgb.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
  if (!match) return rgb;
  const [, r, g, b] = match;
  return `#${[r, g, b].map((c) => Number(c).toString(16).padStart(2, "0")).join("")}`;
}

function resolveColor(value: string | undefined, fallback: string): string {
  if (!value) return fallback;
  return value.startsWith("rgb") ? rgbToHex(value) : value;
}

function resolveFont(tokens: ReferenceStyleTokens | undefined, index: number, fallback: string): string {
  const raw = tokens?.fontFamilies[index];
  if (!raw) return fallback;
  return raw.replace(/["']/g, "").split(",")[0]?.trim() ?? fallback;
}

function renderHeroImage(capture: ReferenceCapture | undefined, sectionType: string): string {
  const firstImage = capture?.imageAssets[0];
  if (!firstImage) return "";

  return `
    {% if section.settings.hero_image != blank %}
      <img
        src="{{ section.settings.hero_image }}"
        alt="{{ section.settings.hero_image_alt }}"
        class="${sectionType}__hero-image"
        loading="eager"
        width="1440"
      >
    {% endif %}
`;
}

function heroImageSettings(capture: ReferenceCapture | undefined): Array<Record<string, unknown>> {
  const firstImage = capture?.imageAssets[0];
  if (!firstImage) return [];

  return [
    { type: "url", id: "hero_image", label: "Hero image URL", default: firstImage.src },
    { type: "text", id: "hero_image_alt", label: "Hero image alt", default: firstImage.alt ?? "" }
  ];
}

function renderMarketingSection(
  sectionType: string,
  analysis: ReferenceAnalysis,
  mapping: ThemeMapping,
  capture?: ReferenceCapture
): string {
  const primarySection = mapping.sections[0];
  const tokens = capture?.styleTokens;
  const bgColor = resolveColor(tokens?.pageBackgroundColor, "#ffffff");
  const textColor = resolveColor(tokens?.bodyTextColor, "#1a1a1a");
  const btnBg = resolveColor(tokens?.primaryButtonBackgroundColor, "#1a1a1a");
  const btnText = resolveColor(tokens?.primaryButtonTextColor, "#ffffff");
  const bodyFont = resolveFont(tokens, 0, "system-ui, sans-serif");
  const headingFont = resolveFont(tokens, 1, bodyFont);
  const heading = capture?.headingOutline[0] ?? primarySection?.heading ?? analysis.title;
  const ctaLabel = capture?.primaryCtas[0]?.label ?? primarySection?.ctaLabel ?? "Shop now";

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="${sectionType} full-width">
  <div class="${sectionType}__content">
    {% if section.settings.eyebrow != blank %}
      <p class="${sectionType}__eyebrow">{{ section.settings.eyebrow }}</p>
    {% endif %}

${renderHeroImage(capture, sectionType)}

    <h1>{{ section.settings.heading }}</h1>
    <p class="${sectionType}__body">{{ section.settings.body }}</p>

    {% if section.settings.cta_label != blank and section.settings.cta_link != blank %}
      <a class="${sectionType}__cta" href="{{ section.settings.cta_link }}">
        {{ section.settings.cta_label }}
      </a>
    {% endif %}

${renderCommerceWiringSnippet(analysis.pageType)}
  </div>
</section>

{% stylesheet %}
  .${sectionType} {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background-color: ${bgColor};
    color: ${textColor};
    font-family: ${bodyFont};
  }

  .${sectionType}__content {
    grid-column: 2;
    padding: 0 24px;
    max-width: 720px;
  }

  .${sectionType}__eyebrow {
    margin: 0 0 1rem;
    text-transform: uppercase;
    letter-spacing: 0.14em;
    font-size: 0.82rem;
  }

  .${sectionType}__hero-image {
    width: 100%;
    height: auto;
    border-radius: 0.5rem;
    margin-bottom: 2rem;
    object-fit: cover;
  }

  .${sectionType} h1 {
    margin: 0;
    font-size: clamp(2.75rem, 7vw, 5rem);
    line-height: 0.95;
    font-family: ${headingFont};
  }

  .${sectionType}__body {
    margin: 1.5rem 0 0;
    max-width: 60ch;
    font-size: 1.1rem;
    line-height: 1.5;
  }

  .${sectionType}__cta {
    display: inline-flex;
    margin-top: 1.75rem;
    padding: 0.95rem 1.4rem;
    border-radius: 999px;
    text-decoration: none;
    color: ${btnText};
    background-color: ${btnBg};
    font-family: inherit;
    font-weight: 600;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: schemaNameForPageType(analysis.pageType),
    settings: [
      { type: "text", id: "eyebrow", label: "Eyebrow", default: analysis.referenceHost },
      { type: "text", id: "heading", label: "Heading", default: heading },
      { type: "textarea", id: "body", label: "Body", default: primarySection?.body ?? analysis.summary },
      { type: "text", id: "cta_label", label: "CTA label", default: ctaLabel },
      { type: "url", id: "cta_link", label: "CTA link" },
      ...heroImageSettings(capture)
    ],
    presets: [{ name: schemaNameForPageType(analysis.pageType) }]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderProductSection(
  sectionType: string,
  analysis: ReferenceAnalysis,
  mapping: ThemeMapping,
  capture?: ReferenceCapture
): string {
  const primarySection = mapping.sections[0];
  const tokens = capture?.styleTokens;
  const bgColor = resolveColor(tokens?.pageBackgroundColor, "#ffffff");
  const textColor = resolveColor(tokens?.bodyTextColor, "#1a1a1a");
  const btnBg = resolveColor(tokens?.primaryButtonBackgroundColor, "#1a1a1a");
  const btnText = resolveColor(tokens?.primaryButtonTextColor, "#ffffff");
  const bodyFont = resolveFont(tokens, 0, "system-ui, sans-serif");
  const headingFont = resolveFont(tokens, 1, bodyFont);
  const heading = capture?.headingOutline[0] ?? primarySection?.heading ?? analysis.title;
  const ctaLabel = capture?.primaryCtas[0]?.label ?? primarySection?.ctaLabel ?? "Add to cart";

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="${sectionType} full-width">
  <div class="${sectionType}__content">
    {% if section.settings.eyebrow != blank %}
      <p class="${sectionType}__eyebrow">{{ section.settings.eyebrow }}</p>
    {% endif %}
    {% if product.featured_image %}
      {{ product.featured_image | image_url: width: 600 | image_tag: class: "${sectionType}__image" }}
    {% endif %}
    <h1>{{ product.title | default: section.settings.heading }}</h1>
    <p class="${sectionType}__body">{{ section.settings.body }}</p>

    {% if product != blank %}
      <div class="${sectionType}__price">{{ product.price | money }}</div>
      {% form 'product', product %}
        <button class="${sectionType}__cta" type="submit">
          {{ section.settings.cta_label }}
        </button>
      {% endform %}
    {% else %}
      <p class="${sectionType}__empty">Connect this template to a product to validate the generated purchase flow.</p>
    {% endif %}

${renderCommerceWiringSnippet(analysis.pageType)}
  </div>
</section>

{% stylesheet %}
  .${sectionType} {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background-color: ${bgColor};
    color: ${textColor};
    font-family: ${bodyFont};
  }

  .${sectionType}__content {
    grid-column: 2;
    padding: 0 24px;
    max-width: 760px;
  }

  .${sectionType}__image {
    width: 100%;
    max-width: 480px;
    border-radius: 0.5rem;
    margin-bottom: 1.5rem;
  }

  .${sectionType}__eyebrow,
  .${sectionType}__empty {
    opacity: 0.7;
  }

  .${sectionType}__image {
    max-width: 100%;
    height: auto;
    border-radius: 1rem;
    margin-bottom: 1.5rem;
  }

  .${sectionType} h1 {
    margin: 0;
    font-size: clamp(2rem, 5vw, 3.5rem);
    line-height: 1.1;
    font-family: ${headingFont};
  }

  .${sectionType}__body {
    margin: 1rem 0 0;
    max-width: 60ch;
    font-size: 1.05rem;
    line-height: 1.6;
  }

  .${sectionType}__price {
    margin-top: 1.5rem;
    font-size: 1.25rem;
    font-weight: 700;
  }

  .${sectionType}__cta {
    margin-top: 1rem;
    padding: 0.95rem 1.4rem;
    border: 0;
    border-radius: 999px;
    color: ${btnText};
    background-color: ${btnBg};
    font-family: inherit;
    font-weight: 600;
    cursor: pointer;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: schemaNameForPageType(analysis.pageType),
    settings: [
      { type: "text", id: "eyebrow", label: "Eyebrow", default: analysis.referenceHost },
      { type: "text", id: "heading", label: "Heading fallback", default: heading },
      { type: "textarea", id: "body", label: "Body", default: primarySection?.body ?? analysis.summary },
      { type: "text", id: "cta_label", label: "CTA label", default: ctaLabel }
    ]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderCollectionSection(
  sectionType: string,
  analysis: ReferenceAnalysis,
  mapping: ThemeMapping,
  capture?: ReferenceCapture
): string {
  const primarySection = mapping.sections[0];
  const tokens = capture?.styleTokens;
  const bgColor = resolveColor(tokens?.pageBackgroundColor, "#ffffff");
  const textColor = resolveColor(tokens?.bodyTextColor, "#1a1a1a");
  const bodyFont = resolveFont(tokens, 0, "system-ui, sans-serif");
  const headingFont = resolveFont(tokens, 1, bodyFont);
  const heading = capture?.headingOutline[0] ?? primarySection?.heading ?? analysis.title;
  const cardBg = resolveColor(tokens?.primaryButtonBackgroundColor, "#f3f4f6");

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="${sectionType} full-width">
  <div class="${sectionType}__content">
    {% if section.settings.eyebrow != blank %}
      <p class="${sectionType}__eyebrow">{{ section.settings.eyebrow }}</p>
    {% endif %}

    <h1>{{ collection.title | default: section.settings.heading }}</h1>
    <p class="${sectionType}__body">{{ section.settings.body }}</p>

    <div class="${sectionType}__grid">
      {% for product in collection.products limit: 8 %}
        <a href="{{ product.url }}" class="${sectionType}__card-link">
          <article class="${sectionType}__card">
            {% if product.featured_image %}
              {{ product.featured_image | image_url: width: 400 | image_tag: class: "${sectionType}__card-image" }}
            {% endif %}
            <h2>{{ product.title }}</h2>
            <p>{{ product.price | money }}</p>
          </article>
        </a>
      {% else %}
        <p class="${sectionType}__empty">Connect this template to a collection to validate the generated browsing flow.</p>
      {% endfor %}
    </div>

${renderCommerceWiringSnippet(analysis.pageType)}
  </div>
</section>

{% stylesheet %}
  .${sectionType} {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background-color: ${bgColor};
    color: ${textColor};
    font-family: ${bodyFont};
  }

  .${sectionType}__content {
    grid-column: 2;
    padding: 0 24px;
  }

  .${sectionType} h1 {
    font-family: ${headingFont};
  }

  .${sectionType}__grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 1rem;
    margin-top: 2rem;
  }

  .${sectionType}__card-link {
    text-decoration: none;
    color: inherit;
    display: block;
  }

  .${sectionType}__card {
    display: block;
    text-decoration: none;
    color: inherit;
    padding: 1rem;
    border-radius: 1rem;
    background: ${cardBg}15;
  }

  .${sectionType}__card-image {
    width: 100%;
    height: auto;
    border-radius: 0.5rem;
    margin-bottom: 0.75rem;
  }

  .${sectionType}__empty {
    opacity: 0.7;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: schemaNameForPageType(analysis.pageType),
    settings: [
      { type: "text", id: "eyebrow", label: "Eyebrow", default: analysis.referenceHost },
      { type: "text", id: "heading", label: "Heading fallback", default: heading },
      { type: "textarea", id: "body", label: "Body", default: primarySection?.body ?? analysis.summary }
    ]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderSection(analysis: ReferenceAnalysis, mapping: ThemeMapping, capture?: ReferenceCapture): string {
  const sectionType = sectionTypeFromPath(mapping.sectionPath);

  if (analysis.pageType === "product_page") {
    return renderProductSection(sectionType, analysis, mapping, capture);
  }

  if (analysis.pageType === "collection_page") {
    return renderCollectionSection(sectionType, analysis, mapping, capture);
  }

  return renderMarketingSection(sectionType, analysis, mapping, capture);
}

function renderTemplate(analysis: ReferenceAnalysis, mapping: ThemeMapping, capture?: ReferenceCapture): string {
  const sectionType = sectionTypeFromPath(mapping.sectionPath);
  const heading = capture?.headingOutline[0] ?? mapping.sections[0]?.heading ?? mapping.title;
  const ctaLabel = capture?.primaryCtas[0]?.label ?? mapping.sections[0]?.ctaLabel ?? "Shop now";

  return JSON.stringify(
    {
      sections: {
        main: {
          type: sectionType,
          settings: {
            eyebrow: mapping.title,
            heading,
            body: mapping.sections[0]?.body ?? mapping.summary,
            mapping_summary: mapping.summary,
            ...(analysis.pageType !== "collection_page" ? { cta_label: ctaLabel } : {}),
            ...(capture?.imageAssets[0] ? { hero_image: capture.imageAssets[0].src } : {}),
            ...(capture?.imageAssets[0]?.alt ? { hero_image_alt: capture.imageAssets[0].alt } : {})
          }
        }
      },
      order: ["main"]
    },
    null,
    2
  );
}

export class ShopifyThemeGenerator {
  constructor(readonly themeWorkspacePath: string) {}

  async generate({ analysis, mapping, capture }: GenerateInput): Promise<{
    artifacts: GeneratedThemeArtifact[];
    generation: GenerationResult;
  }> {
    const artifacts = stableThemeArtifacts[analysis.pageType];
    await mkdir(dirname(join(this.themeWorkspacePath, mapping.sectionPath)), { recursive: true });
    await mkdir(dirname(join(this.themeWorkspacePath, mapping.templatePath)), { recursive: true });

    await writeFile(join(this.themeWorkspacePath, mapping.sectionPath), renderSection(analysis, mapping, capture));
    await writeFile(join(this.themeWorkspacePath, mapping.templatePath), renderTemplate(analysis, mapping, capture));

    const generatedAt = new Date().toISOString();

    return {
      artifacts: [
        {
          kind: "section",
          path: mapping.sectionPath,
          status: "generated",
          description: artifacts.sectionDescription,
          lastWrittenAt: generatedAt
        },
        {
          kind: "template",
          path: mapping.templatePath,
          status: "generated",
          description: artifacts.templateDescription,
          lastWrittenAt: generatedAt
        }
      ],
      generation: {
        generatedAt,
        templatePath: mapping.templatePath,
        sectionPath: mapping.sectionPath
      }
    };
  }
}
