import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  pageTypeLabels,
  stableCommerceArtifact,
  type CommerceEntryPoint,
  type CommerceWiringPlan,
  type GeneratedThemeArtifact,
  type ReferenceAnalysis,
  type StoreSetupPlan,
  type ThemeMapping
} from "@shopify-web-replicator/shared";

type GenerateInput = {
  analysis: ReferenceAnalysis;
  mapping: ThemeMapping;
  storeSetup: StoreSetupPlan;
};

type CommerceWiringGenerationResult = {
  artifact: GeneratedThemeArtifact;
  commerce: CommerceWiringPlan;
};

function buildEntryPoints(analysis: ReferenceAnalysis, storeSetup: StoreSetupPlan): CommerceEntryPoint[] {
  const primaryProduct = storeSetup.products[0];
  const primaryCollection = storeSetup.collections[0];

  if (analysis.pageType === "product_page" && primaryProduct) {
    return [
      {
        label: "Product form",
        target: `/products/${primaryProduct.handle}`,
        behavior: "Uses Shopify product form submission to add items to the native cart."
      },
      {
        label: "Cart review",
        target: "/cart",
        behavior: "Confirms the product form lands in Shopify cart before native checkout."
      }
    ];
  }

  if (analysis.pageType === "collection_page" && primaryCollection) {
    return [
      {
        label: "Collection CTA",
        target: `/collections/${primaryCollection.handle}`,
        behavior: "Routes browsing to the generated collection before add-to-cart."
      },
      {
        label: "Cart review",
        target: "/cart",
        behavior: "Verifies native Shopify cart to checkout handoff after collection browsing."
      }
    ];
  }

  return [
    {
      label: "Primary CTA",
      target: primaryProduct
        ? `/products/${primaryProduct.handle}`
        : primaryCollection
          ? `/collections/${primaryCollection.handle}`
          : "/cart",
      behavior: "Directs the operator to the primary commerce entrypoint before add-to-cart."
    },
    {
      label: "Cart review",
      target: "/cart",
      behavior: "Verifies native Shopify cart to checkout handoff."
    }
  ];
}

function buildQaChecklist(analysis: ReferenceAnalysis): string[] {
  return [
    `Verify ${pageTypeLabels[analysis.pageType]} calls to action resolve to the intended product or collection path.`,
    "Verify add-to-cart behavior uses Shopify-native cart handling.",
    "Verify cart review can continue into the native Shopify checkout path."
  ];
}

function renderSnippet(analysis: ReferenceAnalysis, commerce: CommerceWiringPlan): string {
  const entrypointComment = commerce.entrypoints
    .map((entrypoint) => `  - ${entrypoint.label}: ${entrypoint.target} (${entrypoint.behavior})`)
    .join("\n");
  const checklistComment = commerce.qaChecklist.map((item) => `  - ${item}`).join("\n");
  const primaryTarget = commerce.entrypoints[0]?.target ?? commerce.cartPath;

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Summary: ${commerce.summary}
  Source: ${analysis.sourceUrl}
  Entry points:
${entrypointComment}
  QA checklist:
${checklistComment}
{% endcomment %}

{% liquid
  assign generated_cart_url = routes.cart_url
  assign generated_checkout_url = '/checkout'
%}

<div
  class="generated-commerce-wiring"
  hidden
  data-page-type="{{ page_type | default: '${analysis.pageType}' }}"
  data-cart-url="{{ generated_cart_url }}"
  data-checkout-url="{{ generated_checkout_url }}"
  data-primary-entrypoint="${primaryTarget}"
>
  <span class="generated-commerce-wiring__summary">${commerce.summary}</span>
  <span class="generated-commerce-wiring__checkout">{{ generated_checkout_url }}</span>
</div>
`;
}

function createCommercePlan(analysis: ReferenceAnalysis, storeSetup: StoreSetupPlan): CommerceWiringPlan {
  return {
    plannedAt: new Date().toISOString(),
    snippetPath: stableCommerceArtifact.path,
    summary: `Prepared deterministic commerce wiring plan for ${analysis.title} with native Shopify cart and checkout handoff.`,
    cartPath: "/cart",
    checkoutPath: "/checkout",
    entrypoints: buildEntryPoints(analysis, storeSetup),
    qaChecklist: buildQaChecklist(analysis)
  };
}

export class ShopifyCommerceWiringGenerator {
  readonly #themeWorkspacePath: string;

  constructor(themeWorkspacePath: string) {
    this.#themeWorkspacePath = themeWorkspacePath;
  }

  async generate({ analysis, storeSetup }: GenerateInput): Promise<CommerceWiringGenerationResult> {
    const commerce = createCommercePlan(analysis, storeSetup);
    const outputPath = join(this.#themeWorkspacePath, stableCommerceArtifact.path);

    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, renderSnippet(analysis, commerce), "utf8");

    return {
      artifact: {
        kind: "snippet",
        path: stableCommerceArtifact.path,
        status: "generated",
        description: stableCommerceArtifact.description,
        lastWrittenAt: commerce.plannedAt
      },
      commerce
    };
  }
}
