import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  stableThemeArtifacts,
  type GeneratedThemeArtifact,
  type GenerationResult,
  type ReferenceAnalysis,
  type ThemeMapping
} from "@shopify-web-replicator/shared";

type GenerateInput = {
  analysis: ReferenceAnalysis;
  mapping: ThemeMapping;
};

function asLiquidString(value?: string): string {
  return JSON.stringify(value ?? "");
}

function renderSection(analysis: ReferenceAnalysis, mapping: ThemeMapping): string {
  const primarySection = mapping.sections[0];

  return `{% comment %}
  Generated by Shopify Web Replicator.
  Source: ${analysis.sourceUrl}
  Mapping summary: ${mapping.summary}
{% endcomment %}

<section class="generated-reference full-width">
  <div class="generated-reference__content">
    {% if section.settings.eyebrow != blank %}
      <p class="generated-reference__eyebrow">{{ section.settings.eyebrow }}</p>
    {% endif %}

    <h1>{{ section.settings.heading }}</h1>
    <p class="generated-reference__body">{{ section.settings.body }}</p>
    <p class="generated-reference__meta">{{ section.settings.mapping_summary }}</p>

    {% if section.settings.cta_label != blank and section.settings.cta_link != blank %}
      <a class="generated-reference__cta" href="{{ section.settings.cta_link }}">
        {{ section.settings.cta_label }}
      </a>
    {% endif %}
  </div>
</section>

{% stylesheet %}
  .generated-reference {
    display: grid;
    grid-template-columns: var(--content-grid);
    padding: 80px 0;
    background:
      radial-gradient(circle at top left, rgba(214, 237, 158, 0.9), transparent 28%),
      linear-gradient(180deg, #fffdf5 0%, #eef4df 100%);
  }

  .generated-reference__content {
    grid-column: 2;
    padding: 0 24px;
    max-width: 720px;
  }

  .generated-reference__eyebrow {
    margin: 0 0 1rem;
    text-transform: uppercase;
    letter-spacing: 0.14em;
    font-size: 0.82rem;
  }

  .generated-reference h1 {
    margin: 0;
    font-size: clamp(2.75rem, 7vw, 5rem);
    line-height: 0.95;
  }

  .generated-reference__body,
  .generated-reference__meta {
    margin: 1.5rem 0 0;
    max-width: 60ch;
    font-size: 1.1rem;
    line-height: 1.5;
  }

  .generated-reference__meta {
    font-size: 0.95rem;
    color: #335144;
  }

  .generated-reference__cta {
    display: inline-flex;
    margin-top: 1.75rem;
    padding: 0.95rem 1.4rem;
    border-radius: 999px;
    text-decoration: none;
    color: #fffdf5;
    background-color: #17362b;
  }
{% endstylesheet %}

{% schema %}
${JSON.stringify(
  {
    name: "Generated reference",
    settings: [
      {
        type: "text",
        id: "eyebrow",
        label: "Eyebrow",
        default: analysis.referenceHost
      },
      {
        type: "text",
        id: "heading",
        label: "Heading",
        default: primarySection?.heading ?? analysis.title
      },
      {
        type: "textarea",
        id: "body",
        label: "Body",
        default: primarySection?.body ?? analysis.summary
      },
      {
        type: "textarea",
        id: "mapping_summary",
        label: "Mapping summary",
        default: mapping.summary
      },
      {
        type: "text",
        id: "cta_label",
        label: "CTA label",
        default: primarySection?.ctaLabel ?? "Review generated output"
      },
      {
        type: "url",
        id: "cta_link",
        label: "CTA link"
      }
    ],
    presets: [
      {
        name: "Generated reference"
      }
    ]
  },
  null,
  2
)}
{% endschema %}
`;
}

function renderTemplate(mapping: ThemeMapping): string {
  return JSON.stringify(
    {
      sections: {
        main: {
          type: "generated-reference",
          settings: {
            eyebrow: mapping.title,
            heading: mapping.sections[0]?.heading ?? mapping.title,
            body: mapping.sections[0]?.body ?? mapping.summary,
            mapping_summary: mapping.summary,
            cta_label: mapping.sections[0]?.ctaLabel ?? "Review generated output"
          }
        }
      },
      order: ["main"]
    },
    null,
    2
  );
}

export class ShopifyThemeGenerator {
  constructor(readonly themeWorkspacePath: string) {}

  async generate({ analysis, mapping }: GenerateInput): Promise<{
    artifacts: GeneratedThemeArtifact[];
    generation: GenerationResult;
  }> {
    await mkdir(dirname(join(this.themeWorkspacePath, stableThemeArtifacts.section)), { recursive: true });
    await mkdir(dirname(join(this.themeWorkspacePath, stableThemeArtifacts.template)), { recursive: true });

    await writeFile(join(this.themeWorkspacePath, stableThemeArtifacts.section), renderSection(analysis, mapping));
    await writeFile(join(this.themeWorkspacePath, stableThemeArtifacts.template), renderTemplate(mapping));

    const generatedAt = new Date().toISOString();

    return {
      artifacts: [
        {
          kind: "section",
          path: stableThemeArtifacts.section,
          status: "generated",
          description: "Primary generated landing section output",
          lastWrittenAt: generatedAt
        },
        {
          kind: "template",
          path: stableThemeArtifacts.template,
          status: "generated",
          description: "Generated JSON template that references the stable landing section",
          lastWrittenAt: generatedAt
        }
      ],
      generation: {
        generatedAt,
        templatePath: stableThemeArtifacts.template,
        sectionPath: stableThemeArtifacts.section
      }
    };
  }
}
